### ISSUE TITLE
Users can view the surfboard for sale.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Surfazon#1]
# Motivation
So that the products can be seen by the customer when viewing the site

# Tasks
- [x] Create 'index.html',  'styles.css' and 'main.js'
- [x] Link your Javascript file to your 'index.html'
- [x] Link your CSS file to your 'index.html' as well as bootstrap library
- [x] Title the document in the head title and create an h1 tag in the body for the header
- [x] add image tags and link the surfboard images
- [x] write HTML with included bootstrap

# Wireframe
![image](https://user-images.githubusercontent.com/26953295/27106539-a0a90976-5048-11e7-8ad2-f2c412ec65ed.png)
