### ISSUE TITLE
Users can view details of the surfboard.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Surfazon#2]
# Motivation
The user can see the product details of what he/she may be buying.

# Tasks
- [x] Add properties to the surfboards objects to include description, ID, surf level, and wave type.
- [x] define a function that adds the class attribute 'hide' to container element when clicked.
- [x] create eventListener to surfboard list div that passed hide function when 'clicked'
- [x] write the HTML to reflect what i want the details page to look like
- [x] write the function that renders the DOM to look like the details page
- [x] create event listener that listens for click on surfboards list and adds hide class to surfboard list and removes it from details page

# Wireframe

![surfazon issue-2](https://user-images.githubusercontent.com/26953295/27198818-ae79f8cc-51c8-11e7-99ab-36dea38d787c.png)
