### ISSUE TITLE
Users can add items to their cart.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Surfazon#3]
# Motivation
User can add multiple items to cart before purchasing them 

# Tasks
- [x] Create wireframe to show what adding an item to cart will look like
- [x] Create an object for the cart and have properties be surfboard ID's
- [x] Create function that has the ability to access properties using square bracket and add a quantity when called
- [x] Add an event listener to the button 'Add to Cart' that calls the function to add board to the cart
- [x] User can see a cart logo and a number popup that adds the sum of quantity in their cart
  - [x] Add images to images folder
  - [x] Create the Image element through the DOM 
  - [x] Add attributes to Image to source to the file 'cart.png'
  - [x] Add append function to the event listener of button click to include the image
  - [x] Create a function that adds a counter that increments when the Addcart button is clicked.
- [x] Add style rules to cart so it appears on top right of page

# Wireframe
![surfazon issue-3 1](https://user-images.githubusercontent.com/26953295/27354164-8a066236-55bb-11e7-8aba-42419ba81b8f.png)
