### ISSUE TITLE
Users can view cart.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Surfazon#4]
# Motivation
The user can see the items that he/she are about to purchase in one view.

# Tasks
- [x] Write HTML for one item in cart and keep HTML as a row with view class
- [x] Add button element 'view shopping cart' in surfboard description view
- [x] create function that loops through my cart and adds what is in it to an array of cart items
- [x] write function renderCart that displays shopping cart view and adds elements to the DOM
  - [x] include tax, total and subtotal count
- [x] Add event listener to vew shopping cart button and pass renderCart function
- [x] Add a function that gathers the total price and tax and outputs it to the page.
  - [x] Define a function that gets the total amount dollars in the cart
- [ ] Add event listener to 'keep shopping' button to bring user back to home page
  - [x] Add a button with HTML and style it with CSS
  - [ ] Attach an event listener to the button that swaps views back to home.

# Wireframe

![surfazon issue-4](https://user-images.githubusercontent.com/26953295/27448225-da2a885e-5738-11e7-9c5e-94a677e746d7.png)
